### PR TITLE
Add TODO to pom

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/4)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4#-KxhA3_lmg_qDvAzW9GU:-KxhA3_lmg_qDvAzW9GV:b-f100qs) ([raw file](https://github.com/vaadin/vaadin-form-layout-flow/blob/7f59f8dc6345c04ef8279182f5a9572e6785eba1/pom.xml#L37)):*
> single

`the single` I guess since it's a concrete component

---

*[pom.xml, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4#-KxhAHV-EcHNYne0Z_pP:-KxhAHV0cm7uLdCYg0Dd:br0ka9q) ([raw file](https://github.com/vaadin/vaadin-form-layout-flow/blob/7f59f8dc6345c04ef8279182f5a9572e6785eba1/pom.xml#L38)):*
> 

What's that ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4#-KxhA3_lmg_qDvAzW9GU:-KxhFoYhXBbiWLjZzWA7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-form-layout-flow/blob/7f59f8dc6345c04ef8279182f5a9572e6785eba1/pom.xml#L37)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> single

`the single` I guess since it's a concrete component
</blockquote></details>

Done.

---

*[pom.xml, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4#-KxhAHV-EcHNYne0Z_pP:-KxhDIJqJFi_aRhWgRo-:b-z7me3r) ([raw file](https://github.com/vaadin/vaadin-form-layout-flow/blob/7f59f8dc6345c04ef8279182f5a9572e6785eba1/pom.xml#L38)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> 

What's that ?
</blockquote></details>

I tried to answer that in the code. it is just a reminder for further changes.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4#-KxhA3_lmg_qDvAzW9GU:-KxhGG_zJ-5NoSkzFFq9:b-86z446) ([raw file](https://github.com/vaadin/vaadin-form-layout-flow/blob/7f59f8dc6345c04ef8279182f5a9572e6785eba1/pom.xml#L37)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4#-KxhA3_lmg_qDvAzW9GU:-KxhHLfM3Ynw0Uu2GysS:by5ksbo) ([raw file](https://github.com/vaadin/vaadin-form-layout-flow/blob/7f59f8dc6345c04ef8279182f5a9572e6785eba1/pom.xml#L37)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

How ?
</blockquote></details>

let us change it more significantly. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-form-layout-flow/4)*

**Pull request merged**
